### ISSUE TITLE
Documentation for creating buildpack is incorrect.

### ISSUE THREAD

**Issue by bnanda** [TIBCOSoftware/bwce-buildpack#1]
As per the readme file:

---------------
Download appropriate TIBCO BusinessWorks™ Container Edition 2.0.0 artifacts from https://edelivery.tibco.com. It contains TIBCO BusinessWorks™ Container Edition runtime(bwce_cf.zip).
---------------

However, the bwce_cf.zip is not included in the BWCE installer zip (i.e. TIB_bwce_2.0.0_macosx_x86_64.zip for Mac OSX) downloaded from edelivery. bwce_cf.zip has to be downloaded from reldist, but customers do not have access to reldist.

**Comment by rahulkamdar** [comment]
Please download bwce_cf.zip from 'Container' platform category via
edelivery.tibco.com. The mentioned BWCE installer zip
'TIB_bwce_2.0.0_macosx_x86_64.zip' for Mac OSX is the design-time/Studio
installer. The runtime installation is under the 'Container' platform
categories.
