### ISSUE TITLE
Getting Error when compile

### ISSUE THREAD

**Issue by maps90** [TIBCOSoftware/bwce-buildpack#8]
What branch are you using ?
master [f715c4b5b3d4ca46e545a6f7149f2d895bf55edb]

What is your BWCE version?
2.3.3 

What happen ?
``` 
   Running BWCE buildpack
   mv: cannot stat 'bin/*': No such file or directory
   Exit status 0
```

I'm certain that the error coming from bin/compile line 161
```
mkdir -p tibco.home/addons/bin/ && mv bin/* "$_"
```

can you help me on this @nitish29 ?

**Comment by nitish29** [comment]
Hey @maps90, 

Can you provide a background of what you are trying to accomplish? Are you trying to integrate a plugin or copy a zip?
